name: gs2mesh
channels:
  - pytorch
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - cudatoolkit=11.8
  - plyfile
  - python=3.11
  - pip=22.3.1
  - pytorch
  - torchaudio
  - torchvision
  - tqdm
  - colmap
  - pip:
    - third_party/gaussian-splatting/submodules/diff-gaussian-rasterization
    - third_party/gaussian-splatting/submodules/simple-knn
    - segment_anything
    - scipy
    - tensorboard
    - opt_einsum
    - imageio
    - opencv-python
    - scikit-image
    - einops
    - matplotlib
    - plotly
    - open3d
    - jupyterlab
    - k3d
    - trimesh
    - ipympl
